version: '3.5'

services:
    example-redis:
        image: redis
        ports:
            - 6379:6379
    example-frontend:
        image: example-frontend 
        ports:
            - 5000:5000
    example-backend:
        image: example-backend 
        ports:
            - 8080:8080
        environment: 
            - REDIS_HOST=example-redis

