version: '3.5'

services:
    example-frontend:
        image: example-frontend 
        container_name: example-frontend
        ports:
            - 5000:5000
        depends_on: 
            - example-backend
    example-backend:
        image: example-backend 
        container_name: example-backend
        ports:
            - 8080:8080
        environment: 
            - REDIS_HOST=example-redis
            - POSTGRES_HOST=example-postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=example
            - POSTGRES_DATABASE=postgres
        depends_on: 
            - example-postgres
            - example-redis
    example-postgres:
        image: postgres
        container_name: example-postgres
        restart: unless-stopped
        environment: 
            - POSTGRES_PASSWORD=example
        volumes: 
            - ./database:/var/lib/postgresql/data
    example-redis:
        image: redis
        container_name: example-redis
        ports:
            - 6379:6379