version: '3.5'

services:
    example-redis:
        image: redis
        container_name: example-redis
        ports:
            - 6379:6379
    example-frontend:
        image: example-frontend 
        container_name: example-frontend
        ports:
            - 5000:5000
    example-backend:
        image: example-backend 
        container_name: example-backend
        ports:
            - 8080:8080
        environment: 
            - REDIS_HOST=example-redis
            - POSTGRES_HOST=example-postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=example
            - POSTGRES_DATABASE=postgres
    example-postgres:
        image: postgres
        container_name: example-postgres
        restart: unless-stopped
        environment: 
            - POSTGRES_PASSWORD=example
    example-nginx:
        image: nginx
        container_name: example-nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80